            - name: Godot Setup
  # You may pin to the exact commit or the version.
  # uses: lihop/godot-setup@f62f7730e1811dc58bb7edc426c1bdbd80bb0c08
  uses: lihop/godot-setup@v2.1.3
  with:
    # Godot version to use
    version: # default is 3.5.1-stable
    # 64 or 32 bit build
    bits: # optional, default is 64
    # Use the Mono build
    mono: # optional
    # Name of the Godot executable that will be added to PATH
    alias: # optional, default is godot
    # Whether to save/restore Godot download (and mesa-dist-win on Windows runners) to/from cache
    cache: # optional, default is true
    # Whether to download export templates
    export-templates: # optional
    # 
    github-token: # optional, default is ${{ github.token }}
          
